# Generated by Django 5.2.6 on 2025-09-12 03:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='about_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('cv', models.FileField(upload_to='cv/')),
                ('cellphone', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='catalog/')),
                ('file_title', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mon_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('visitor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('visitor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('visitor_subject', models.CharField(blank=True, max_length=500, null=True)),
                ('visitor_message', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='landing/')),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('diplome_or_post', models.CharField(max_length=50)),
                ('entreprise_or_school', models.CharField(max_length=50)),
                ('short_resume', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('percentage', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='testi_cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visitors', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog post title', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL slug (auto-generated if empty)', max_length=200, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle', max_length=300, null=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short description/summary', max_length=500, null=True)),
                ('content', models.TextField(help_text='Main blog content')),
                ('featured_image', models.ImageField(blank=True, help_text='Main blog image', null=True, upload_to='blog/images/%Y/%m/%d/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for featured image (for SEO and accessibility)', max_length=200, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Publish this blog post')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When to publish this post')),
                ('date_issue', models.DateField(auto_now_add=True, help_text='Original creation date')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title (60 chars max)', max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (160 chars max)', max_length=160, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords (comma separated)', max_length=200, null=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('reading_time', models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes')),
                ('allow_comments', models.BooleanField(default=True, help_text='Allow comments on this post')),
                ('featured', models.BooleanField(default=False, help_text='Feature this post on homepage')),
                ('status', models.BooleanField(default=True, help_text='Active/Inactive status')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Blog post author', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='portefolio.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='blog_posts', to='portefolio.blogtag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-publish_date', '-date_add'],
                'indexes': [models.Index(fields=['slug'], name='portefolio__slug_0176ec_idx'), models.Index(fields=['publish_date'], name='portefolio__publish_68a75e_idx'), models.Index(fields=['is_published', 'status'], name='portefolio__is_publ_63723a_idx'), models.Index(fields=['featured'], name='portefolio__feature_99299f_idx')],
            },
        ),
    ]
