# Generated by Django 5.1.1 on 2024-09-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about_me',
            name='cellphone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about_me',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about_me',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about_me',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='file_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='visitor_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='visitor_subject',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='landing',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='link_name',
            name='link_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='diplome_or_post',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='entreprise_or_school',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='short_resume',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testi_cards',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
