# Generated by Django 5.1.1 on 2024-09-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0002_alter_about_me_address_alter_about_me_cellphone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_me',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
    ]
