# Generated by Django 5.1.1 on 2024-09-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0003_remove_about_me_description_remove_blog_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
