# Generated by Django 5.1.1 on 2024-09-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0004_remove_service_image_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
