# Generated by Django 5.1.1 on 2024-09-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0005_alter_skill_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='short_resume',
            field=models.TextField(),
        ),
    ]
