# Generated by Django 5.1.1 on 2024-09-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0006_alter_resume_short_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='short_resume',
            field=models.CharField(max_length=250),
        ),
    ]
