# Generated by Django 5.1.1 on 2024-10-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0008_alter_contact_address_alter_contact_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
