# Generated by Django 5.1.1 on 2024-10-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0010_alter_blog_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='discord_link',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='flickr_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='nextdoor_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='parler_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='pinterest_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='quora_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='reddit_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='snap_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='telegram_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='tiktok_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='tumblr_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='vimeo_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='wechat_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='whatsapp_link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Link_name',
        ),
    ]
