# Generated by Django 5.1.1 on 2024-10-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0011_rename_discord_link_sociallink_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visitors', models.IntegerField(default=0)),
            ],
        ),
    ]
