# Generated by Django 5.2.6 on 2025-09-09 22:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0012_visitorcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_issue',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
