# Generated by Django 5.2.6 on 2025-09-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0013_about_me_description_project_date_issue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
